version: '3.7'
services:
    app:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certs:/etc/nginx/certs
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
