version: '3.7'
services:
    app:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../pilarlondonng/certs:/etc/nginx/certs
            - ../pilarlondonng/nginx.conf:/etc/nginx/conf.d/default.conf
